### ISSUE TITLE
Arch Linux Package

### ISSUE THREAD

**Issue by Swivelgames** [scylladb/scylla-manager-issues#6]
Would it be possible to create an AUR package for `scylla-manager`, for those of us on Arch-based operating systems? Neither Ubuntu/Debian or RHEL/CentOS are related to Arch Linux. Currently, the only real solution is to install dpkg or yum on Arch, or to build and install Scylla from source.

Naturally, creating an AUR package would probably be similar to building and installing Scylla from source, but at least it would be automated in a way that would make it less cumbersome to get up and running.

**Comment by mmRoshani** [comment]
It would be nice to have `scylla-manager` on aur.
I don't know why it takes so long to respond to this issue.

**Comment by tzach** [comment]
Closing, as we have no plan to build Arc packages for Scylla Manager.
Note that you can build the release yourself:

- Clone the repo
- Access repo_folder/dist
- Run make release

See the Scylla Manager license here https://github.com/scylladb/scylla-manager#license
